### PR TITLE
Update tutorials with the new style

### PR DESCRIPTION
**Pull request by ebadawy**
Here I've updated the tutorials under 'demo' section  to the new style of Bonecard.

### CODE REVIEW

**Comment by jadonk** [comment]
Anything left to be merged here? @ehab93

**Comment by ehab93** [comment]
AFAIR this PR is important as it has some fixes to bugs in the current master.

**Comment by jadonk** [comment]
@ehab93 any chance of a rebase with minimized deltas per patch?

**Comment by ehab93** [comment]
@jadonk , sure I can do a rebase with the current master, but not sure what you mean by "minimized deltas per patch"?

**Comment by ebadawy** [comment]
@jadonk , I don't think this PR is safe to be merged right now, found some bugs after the last rebase.

**Pull request closed without merging**
